/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Capability = {
  [k: string]: unknown;
} & {
  title: I18NObject;
  desc?: I18NObject;
  type: "boolean" | "number" | "string" | "enum";
  getable?: boolean;
  setable?: boolean;
  icon?: string;
  insights?: boolean;
  insightsTitleTrue?: I18NObject;
  insightsTitleFalse?: I18NObject;
  chartType?: "line" | "area" | "stepLine" | "column" | "spline" | "splineArea" | "scatter";
  decimals?: number;
  min?: number;
  max?: number;
  step?: number;
  units?: I18NObject;
  values?: {
    id: string;
    title: I18NObject;
    [k: string]: unknown;
  }[];
  uiComponent?:
    | ("thermostat" | "media" | "toggle" | "slider" | "ternary" | "button" | "color" | "picker" | "sensor" | "battery")
    | null;
  [k: string]: unknown;
} & (
    | {
        type?: "enum";
        [k: string]: unknown;
      }
    | {
        type?: "boolean" | "number" | "string";
        [k: string]: unknown;
      }
  );
export type I18NObject =
  | string
  | {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^.*$".
       */
      [k: string]: string;
    };
