/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type I18NObject =
  | string
  | {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^.*$".
       */
      [k: string]: string;
    };
export type DriverSettings = (
  | {
      type: "text" | "password" | "textarea" | "label";
      id: string | number;
      label: I18NObject;
      hint?: I18NObject;
      value?: string;
      pattern?: string;
      highlight?: true;
      zwave?: ZwaveSetting;
      [k: string]: unknown;
    }
  | {
      type: "number" | "slider";
      id: string | number;
      label: I18NObject;
      hint?: I18NObject;
      value?: number;
      units?: I18NObject;
      attr?: {
        min?: number;
        max?: number;
        step?: number;
        [k: string]: unknown;
      };
      min?: number;
      max?: number;
      step?: number;
      highlight?: true;
      zwave?: ZwaveSetting;
      [k: string]: unknown;
    }
  | {
      type: "radio" | "dropdown";
      id: string | number;
      label: I18NObject;
      hint?: I18NObject;
      value?: string;
      values: {
        id: string;
        label: I18NObject;
        [k: string]: unknown;
      }[];
      highlight?: true;
      zwave?: ZwaveSetting;
      [k: string]: unknown;
    }
  | {
      type: "checkbox";
      id: string | number;
      label: I18NObject;
      hint?: I18NObject;
      value?: boolean;
      highlight?: true;
      zwave?: ZwaveSetting;
      [k: string]: unknown;
    }
  | {
      type: "group";
      label: I18NObject;
      children: DriverSettings;
      highlight?: true;
      zwave?: ZwaveSetting;
      [k: string]: unknown;
    }
)[];
export type Integrity = string;
export type AppSettings = (
  | {
      type: "text" | "password" | "textarea" | "label";
      id: string;
      title: I18NObject;
      hint?: I18NObject;
      value?: string;
      pattern?: string;
      [k: string]: unknown;
    }
  | {
      type: "number" | "slider";
      id: string;
      title: I18NObject;
      hint?: I18NObject;
      value?: number;
      units?: I18NObject;
      min?: number;
      max?: number;
      step?: number;
      [k: string]: unknown;
    }
  | {
      type: "radio" | "dropdown";
      id: string;
      title: I18NObject;
      hint?: I18NObject;
      value?: string;
      values: {
        id: string;
        title: I18NObject;
        [k: string]: unknown;
      }[];
      [k: string]: unknown;
    }
  | {
      type: "checkbox";
      id: string;
      title: I18NObject;
      hint?: I18NObject;
      value?: boolean;
      [k: string]: unknown;
    }
  | {
      type: "group";
      title: I18NObject;
      children: AppSettings;
      [k: string]: unknown;
    }
)[];

export interface App {
  id: string;
  name: I18NObject;
  description?: I18NObject;
  author: Author;
  images?: Images;
  version: string;
  compatibility: string;
  sdk?: number;
  platforms?: ("cloud" | "local")[];
  platformLocalRequiredFeatures?: ("nfc" | "speaker" | "ledring" | "matter" | "camera-streaming")[];
  platformLocalOptionalFeatures?: ("nfc" | "speaker" | "ledring" | "matter" | "camera-streaming")[];
  runtime?: "nodejs" | "python";
  pythonVersion?: string;
  pythonPackages?: string[];
  tags?: I18NArray;
  permissions?: string[];
  bugs?: {
    url?: string;
    [k: string]: unknown;
  };
  homepage?: string;
  support?: string;
  source?: string;
  athomForumDiscussionId?: number;
  homeyCommunityTopicId?: number;
  category?: string | string[];
  contributors?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(developers|translators)$".
     */
    [k: string]: Author[];
  };
  contributing?: {
    donate?: {
      githubSponsors?: {
        username?: string;
      };
      bunq?: {
        username?: string;
      };
      patreon?: {
        username?: string;
      };
      paypal?: {
        username?: string;
        email?: string;
        fundraiserCharityId?: number;
        currency?: string;
      };
    };
    [k: string]: unknown;
  };
  screensavers?: {
    name?: string;
    title?: I18NObject;
    [k: string]: unknown;
  }[];
  capabilities?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.*$".
     */
    [k: string]: {
      [k: string]: unknown;
    };
  };
  drivers?: {
    id: string;
    name: I18NObject;
    class: string;
    capabilities: string[];
    capabilitiesOptions?: {
      [k: string]: unknown;
    };
    images?: Images;
    deprecated?: true;
    discovery?: string;
    energy?: {
      approximation?:
        | {
            usageOn: number;
            usageOff: number;
          }
        | {
            usageConstant: number;
          };
      cumulative?: true;
      cumulativeImportedCapability?: string;
      cumulativeExportedCapability?: string;
      electricCar?: true;
      evCharger?: true;
      homeBattery?: true;
      meterPowerImportedCapability?: string;
      meterPowerExportedCapability?: string;
      /**
       * @minItems 1
       */
      batteries?: [string, ...string[]];
      [k: string]: unknown;
    };
    pair?: {
      id: string;
      template?: string;
      options?: {
        [k: string]: unknown;
      };
      navigation?: {
        prev?: string;
        next?: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }[];
    settings?: DriverSettings;
    firmwareUpdates?: ZigbeeFirmwareUpdates;
    gtin?: string | string[];
    matter?: MatterDevice;
    zwave?: ZwaveDevice;
    zigbee?: ZigbeeDevice;
    rf433?: {
      satelliteMode?: boolean;
      [k: string]: unknown;
    };
    infrared?: {
      satelliteMode?: boolean;
      [k: string]: unknown;
    };
    platforms?: ("cloud" | "local")[];
    connectivity?: ("lan" | "cloud" | "ble" | "zwave" | "zigbee" | "infrared" | "rf433" | "rf868" | "matter")[];
    [k: string]: unknown;
  }[];
  flow?: {
    triggers?: FlowCard[];
    conditions?: FlowCard[];
    actions?: FlowCard[];
    [k: string]: unknown;
  };
  signals?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(433|868|ir)$".
     */
    [k: string]: {
      [k: string]: unknown;
    };
  };
  brandColor?: string;
  discovery?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.*$".
     */
    [k: string]: {
      type: "mdns-sd" | "ssdp" | "mac";
      id?: string;
      conditions?: {
        field: string;
        match: {
          type: "string" | "regex";
          value: string;
        };
      }[][];
      "mdns-sd"?: {
        name: string;
        protocol: "tcp" | "udp";
      };
      ssdp?: {
        search: string;
      };
      mac?: {
        /**
         * @minItems 1
         * @maxItems 32
         */
        manufacturer: [[number, number, number], ...[number, number, number][]];
      };
    };
  };
  widgets?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.*$".
     */
    [k: string]: {
      name: I18NObject;
      height?: number | string;
      transparent?: boolean;
      settings?: unknown[];
      devices?: {
        type: "global" | "app";
        singular: boolean;
        filter?: {
          class?: string;
          capabilities?: string;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      api?: {
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^.*$".
         */
        [k: string]: {
          method: "GET" | "POST" | "PUT" | "DELETE";
          path: string;
          [k: string]: unknown;
        };
      };
      id: string;
      deprecated?: boolean;
      [k: string]: unknown;
    };
  };
  settings?: AppSettings;
  [k: string]: unknown;
}
export interface Author {
  name: string;
  email?: string;
  website?: string;
  [k: string]: unknown;
}
export interface Images {
  large: string;
  small: string;
  xlarge?: string;
}
export interface I18NArray {
  /**
   * This interface was referenced by `I18NArray`'s JSON-Schema definition
   * via the `patternProperty` "^.*$".
   */
  [k: string]: string[];
}
export interface ZwaveSetting {
  index: number;
  size: 1 | 2 | 4;
  signed?: boolean;
  [k: string]: unknown;
}
export interface ZigbeeFirmwareUpdates {
  wakeInstruction?: I18NObject;
  queryNextImageTimeout?: number;
  minImageBlockPeriod?: number;
  maxImageBlockSize?: number;
  imageBlockRequestTimeout?: number;
  upgradeEndRequestTimeout?: number;
  upgradeEndDelay?: number;
  postUpgradeAnnounceTimeout?: number;
  /**
   * @minItems 1
   */
  updates: [ZigbeeFirmwareUpdate, ...ZigbeeFirmwareUpdate[]];
}
export interface ZigbeeFirmwareUpdate {
  changelog: I18NObject;
  device: ZigbeeFirmwareUpdateDevice;
  /**
   * @minItems 1
   */
  files: [ZigbeeFirmwareUpdateFile, ...ZigbeeFirmwareUpdateFile[]];
}
export interface ZigbeeFirmwareUpdateDevice {
  manufacturerName: string | string[];
  productId: string | string[];
}
export interface ZigbeeFirmwareUpdateFile {
  fileVersion: number;
  imageType: number;
  manufacturerCode: number;
  minFileVersion?: number;
  maxFileVersion?: number;
  minHardwareVersion?: number;
  maxHardwareVersion?: number;
  size: number;
  name: string;
  integrity: Integrity;
}
export interface MatterDevice {
  vendorId: number | number[];
  productId: number | number[];
  deviceVendorId?: number | number[];
  deviceProductName?: string | string[];
  learnmode?: {
    image?: string;
    instruction: I18NObject;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ZwaveDevice {
  manufacturerId: number | number[];
  productTypeId: number | number[];
  productId: number | number[];
  learnmode?: {
    image?: string;
    instruction: I18NObject;
    [k: string]: unknown;
  };
  associationGroups?: number[];
  associationGroupsMultiChannel?: number[];
  associationGroupsOptions?: {
    hint?: I18NObject;
    [k: string]: unknown;
  };
  wakeUpInterval?: number;
  defaultConfiguration?: {
    id: number;
    size: 1 | 2 | 4;
    value: number | string;
    multiChannelNodes?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
export interface ZigbeeDevice {
  manufacturerName: string | string[];
  productId: string | string[];
  endpoints: {
    [k: string]: {
      clusters?: number[];
      bindings?: number[];
    };
  };
  learnmode?: {
    image?: string;
    instruction: I18NObject;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface FlowCard {
  id: string;
  title: I18NObject;
  titleFormatted?: I18NObject;
  deprecated?: true;
  highlight?: true;
  advanced?: true;
  platforms?: ("cloud" | "local")[];
  droptoken?: ("boolean" | "number" | "string" | "image") | ("boolean" | "number" | "string" | "image")[];
  tokens?: {
    name: string;
    type?: "boolean" | "number" | "string" | "image";
    title: I18NObject;
    example?: I18NObject | number | boolean;
    [k: string]: unknown;
  }[];
  args?: (
    | {
        name: string;
        type: "device";
        filter:
          | string
          | {
              [k: string]: unknown;
            };
        [k: string]: unknown;
      }
    | {
        title?: I18NObject;
        name: string;
        type: "text" | "autocomplete" | "device" | "date" | "time" | "color" | "checkbox" | "code";
        placeholder?: I18NObject;
        filter?:
          | string
          | {
              [k: string]: unknown;
            };
        items?: "variable" | "flow_or_advanced_flow" | "user";
        [k: string]: unknown;
      }
    | {
        title?: I18NObject;
        name: string;
        type: "number" | "range";
        min?: number;
        max?: number;
        step?: number;
        label?: I18NObject;
        labelMultiplier?: number;
        labelDecimals?: number;
        [k: string]: unknown;
      }
    | {
        title?: I18NObject;
        name: string;
        type: "dropdown";
        values: {
          id: string;
          title?: I18NObject;
          [k: string]: unknown;
        }[];
        [k: string]: unknown;
      }
    | {
        title?: I18NObject;
        name: string;
        type: "multiselect";
        conjunction: "and" | "or";
        values: {
          id: string;
          title: I18NObject;
          [k: string]: unknown;
        }[];
        [k: string]: unknown;
      }
  )[];
  [k: string]: unknown;
}
